configuration reading
neuroevolution-ai/NeuroEvolution-CTRNN_new pull request #41
Opened 2020-12-13 11:13 UTC by bjuergens

implements #20

2020-12-13 11:14 UTC, bjuergens commented
Done: 

* unit test, 
* proof of concept

not yet done: 

* registering types via mixin
* registering all types

2020-12-13 11:30 UTC, bjuergens commented
also todo unit tests:

* expected type-error, when missing attribute that is required
* expected type-error when additional attribute that is not (e.g. because typo in optional attribute)
* expected KeyError when attribute `type` is not a registered type.

2020-12-14 10:42 UTC, bjuergens commented
soweit fertig. Bitte review @pdeubel 

Ich denke mit diesen Änderungen wird es in Zukunft sehr bequem sein neue config-attribute hinzuzufügen.

2020-12-16 13:04 UTC, pdeubel requested changes
Finde ich sehr gut gelöst :+1: Die Error Meldung könnte man noch anpassen aber ansonsten passts.

Eine ganz kleine Sache: manchmal wurden Single und Double Quotes gemischt, im Programm nutzen wir sonst eigentlich Double Quotes (find ich persönlich schöner). Bei den Stellen hab ich Code Changes vorgeschlagen.

2020-12-20 09:25 UTC, merged